apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: tinywebsite
    tier: frontend
spec:
  type: NodePort
  selector:
    app: tinywebsite
    tier: frontend
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 8001
    protocol: TCP
    name: http
