apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-exporter-instance
  namespace: default
spec:
  project: default

  source:
    repoURL: "git@git.ringcentral.com:rcvdevops/kubernetes/instances/gitlab-ci-pipelines-exporter-instance.git"
    targetRevision: "implementation"
    path: .
  values:
    gitlab-ci-pipelines-exporter:
      imagePullSecrets:
        - name: "docker-registry"

  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

