apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    namespace: default
data:
    username: YWRtaW4=
    password: ENC[AES256_GCM,data:qAWw5muObf3ESp4ril39yg==,iv:jU/3/MFwsZBuvi1y0mIMktw6F7OowAKOoyT/GucvXGY=,tag:fqXJyZh3IqwPJ/WekujugQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-11T14:41:33Z"
    mac: ENC[AES256_GCM,data:m6+PXUJyCKnIr4+JgsIot2+fPrcebwmhgBTYaxyU9SbrYPhrIPqWIcF5gGz0rXWYioezNnYOu6taRXwVNqV+IDDE12FA+IjuYPUGof38hH/2ppHhI26V8u08D8uUPqt1znLkxqN9KExgMaXloGsSE5zgnf8rQA3AlfgP7a2e1qw=,iv:AGErVr1iuol6ey/mfGtY5Qf20LyoWPogpQKp1EAMjjY=,tag:EXYuzv57F2+Bi9X629o+Hw==,type:str]
    pgp:
        - created_at: "2022-05-11T14:41:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAygqAoM2l3aHAQv+PMSvCMrJfLISjVud4tothRhk0R/fGHIPilyTgM3l1n/H
            K7gCECq66rS2W5Ym6B79+sbirmtTXrLMAMTu1f9o3yygB/dUHnU46mWg7D2p6Vdk
            q+1LmisqJwYYOTW93W4vwMWgKpw5VXshIH4z6ra5grDSS7YM6XqiMljMCNNmxd+z
            Xjns8A75M0FsCnMNpQDOPkJetLgP4U0+GBrrIw4hwSXcPebUoOHpPkM0ODEpA9Dx
            RGzERT5xjlMvV6EJnVQLNu9J59uMWVhq7fpgQF6si+fSgPom/khLg5cDihDfIa+e
            77YnRnxur0A1OsNnnYWKz0KFYlV+5sWKFpk4fmQ+/j0NVcJImIJ5TIpZsvYHfEX2
            srshpuSMmlfZ9GKqeLmrZgIiv0ExMle/Jf8ZPi6Onn3iwf43dPyskFjlfVd0sIwJ
            1VWgtor2X2EATO2FC078RK2S+BsnR/vT7oWDQng/yLEI6AO2xyExgRbtVZWXVpHu
            79+aZQn4DAkURrf9VObW0l4Bh6YtwpaMFsyb2oY8/7c8r5OeS3UfDTG/KCdeGQn5
            nsy8UZNEdSihk4UR6/ZvQq27TDo1r2BWd8IUKLu/Z7sF+dvL8hEL7XJ/lcCdL6vB
            4dtOpSSN8toYSia67jgW
            =P/FX
            -----END PGP MESSAGE-----
          fp: 59BF4832B84ED3D817D4B84ECE82D61D3581421F
    encrypted_regex: password|pin
    version: 3.7.2
